version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5


jobs:

  test-python:
    parameters:
      python-version:
        type: string
    docker:
      - image: cimg/python:<< parameters.python-version >>
    environment:
      # cimg/python uses pyenv instead of venv
      VIRTUAL_ENV: ${PYENV_ROOT}
    steps:
      - checkout
      - run: git submodule sync && git submodule update --init
      - run: sudo make deps-ubuntu
      - run: make install
      - run: make deps-test
      - run: mkdir test-results
      - run:
          name: run tests
          command: make test PYTEST_ARGS="-vv --junitxml=test-results/test.xml"
          no_output_timeout: 30m
      - store_test_results:
          path: test-results
      - run: make test-cli
      - run: 
          command: make coverage
          no_output_timeout: 30m
      - codecov/upload
    resource_class: large

workflows:
  build:
    jobs:
      - test-python:
          matrix:
            parameters:
              python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

