name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch: # run manually

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # we need tags for docker version tagging
        fetch-tags: true
        fetch-depth: 0
    - name: Checkout git submodules too
      run: git submodule sync && git submodule update --init
    - # Activate cache export feature to reduce build time of images
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERIO_USERNAME }}
        password: ${{ secrets.DOCKERIO_PASSWORD }}
    - name: define unversioned fully qualified docker image names
      run: echo "DOCKER_TAG='docker.io/ocrd/tesserocr ghcr.io/ocr-d/tesserocr'" >> $GITHUB_ENV
    - name: Build the Docker image
      # build both tags at the same time
      run: make DOCKER_TAG="${{ env.DOCKER_TAG }}" docker
    - name: Smoke Test the Docker image
      run: make DOCKER_TAG="${{ env.DOCKER_TAG }}" docker-smoke-test
    - name: Push to Dockerhub and Github Container Registry
      run: make DOCKER_TAG="${{ env.DOCKER_TAG }}" docker-push
    
